#!/usr/bin/env bash


getlock () {
  # $1 = db
  # $2 = table
  # $3 = record

  if [[ $3 ]] ; then
    # don't add the lock suffix to simplify the parameter expansion later
    # in case we need to get the lock for subfolders
    lock=db.$1/table.$2/records/record.$3/
  else
    lock=db.$1/table.$2/records/
  fi

  locked=false

  until mkdir "$lock/lock" 2> /dev/null; do
    $locked && continue
    echo "Record locked by $(< "$lock/lock/pid"), waiting" >&2
    locked=true
  done

  # lock all the records
  if [[ ! $3 ]] ; then
    for file in "$lock"* ; do
      getlock "$1" "$2" "${file#"$lock"}"
    done
  fi

  echo $$ > "$lock/lock/pid"
}


releaselock () {
  if [[ $3 ]] ; then
    lock=db.$1/table.$2/records/record.$3/
  else
    lock=db.$1/table.$2/records/
  fi
  rm -rf "$lock/lock"
}



write () {
  # $1 = db
  # $2 = table
  # $3 = record
  # $4 = sql statement reduced to a single record
}



parsesql () {
  aklsdfa
}



